version: 2.1

jobs:
  build_and_push_image:
    docker:
      - image: cimg/base:stable
    parameters:
      docker-username:
        type: env_var_name
        default: DOCKER_LOGIN
      docker-password:
        type: env_var_name
        default: DOCKER_PASSWORD
    steps:
      - setup_remote_docker:
          version: 20.10.23
      - run:
            name: Docker login
            command: |
              echo "$<<parameters.docker-password>>" \
                | docker login -u "$<<parameters.docker-username>>" --password-stdin
      - checkout
      - run: docker buildx create --use && docker buildx build --pull --platform linux/amd64,linux/arm64 -t yusukeito/swift-basic:${CIRCLE_BRANCH} --push .

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push_image
