version: 2.1

jobs:
  dockerbuild:
    docker:
      - image: docker:dind
    parameters:
      qemu-user-static-version:
          default: 5.2.0-2
          type: string
      version:
          default: 0.5.1
          description: buildx version
          type: string
    steps:
      - setup_remote_docker:
          version: 20.10.2
      - checkout
      - run:
            name: Install Docker buildx
            command: |
              apk add curl
              mkdir -p ~/.docker/cli-plugins
              baseUrl="https://github.com/docker/buildx/releases/download"
              fileName="buildx-v<< parameters.version >>.linux-amd64"
              url="${baseUrl}/v<< parameters.version >>/${fileName}"
              curl -sSL -o ~/.docker/cli-plugins/docker-buildx $url
              chmod a+x ~/.docker/cli-plugins/docker-buildx
      - run:
            name: Prepare docker buildx
            command: |
              docker buildx install
              docker version
              docker buildx version
              docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
              docker context create xbuilder
              docker buildx create xbuilder --name xbuilder --use
              docker buildx inspect --bootstrap
      - run: docker buildx build --pull --platform linux/amd64,linux/arm64 -t yusukeito/swift-basic:${CIRCLE_BRANCH} .

workflows:
  version: 2
  dockerbuild_test:
    jobs:
      - dockerbuild
